<a href="https://colab.research.google.com/github/ravinnd3/Generative-AI-Full-Course/blob/main/Text_Representation_word_embeddings_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Some common terms to remember:

Corpus

Vocabulary

Document

Word

# Bag of words

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({'text':['people watch youtube','youtube watch youtube','people write comment','youtube write comment'],'output':[1,1,0,0]})
df

text  output
0   people watch youtube       1
1  youtube watch youtube       1
2   people write comment       0
3  youtube write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df['text'])

In [7]:
print(cv.vocabulary_)

{'people': 1, 'watch': 2, 'youtube': 4, 'write': 3, 'comment': 0}


In [8]:
bow.toarray()

array([[0, 1, 1, 0, 1],
       [0, 0, 1, 0, 2],
       [1, 1, 0, 1, 0],
       [1, 0, 0, 1, 1]])

In [11]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 1 1 0 1]]
[[0 0 1 0 2]]
[[1 1 0 1 0]]
[[1 0 0 1 1]]


In [12]:
# to pass into model
x = bow.toarray()
y = df['output']

# N-grams

In [22]:
# Bi-grams
cv = CountVectorizer(ngram_range=(2,2))

df = pd.DataFrame({'text':['people watch youtube','youtube watch youtube','people write comment','youtube write comment'],'output':[1,1,0,0]})
df

text  output
0   people watch youtube       1
1  youtube watch youtube       1
2   people write comment       0
3  youtube write comment       0

In [23]:
bow = cv.fit_transform(df['text'])

In [24]:
print(cv.vocabulary_)

{'people watch': 0, 'watch youtube': 2, 'youtube watch': 4, 'people write': 1, 'write comment': 3, 'youtube write': 5}


In [25]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())


[[1 0 1 0 0 0]]
[[0 0 1 0 1 0]]
[[0 1 0 1 0 0]]


In [26]:
#Tri gram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [27]:
bow = cv.fit_transform(df['text'])

In [28]:
print(cv.vocabulary_)

{'people watch youtube': 0, 'youtube watch youtube': 2, 'people write comment': 1, 'youtube write comment': 3}


In [29]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 0 0 0]]
[[0 0 1 0]]
[[0 1 0 0]]


# TF-IDF (Term frequency- Inverse document frequency)

In [30]:
df = pd.DataFrame({'text':['people watch youtube','youtube watch youtube','people write comment','youtube write comment'],'output':[1,1,0,0]})
df

text  output
0   people watch youtube       1
1  youtube watch youtube       1
2   people write comment       0
3  youtube write comment       0

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()

In [32]:
arr = tf.fit_transform(df['text']).toarray()

In [33]:
arr

array([[0.        , 0.61366674, 0.61366674, 0.        , 0.49681612],
       [0.        , 0.        , 0.52546357, 0.        , 0.8508161 ],
       [0.57735027, 0.57735027, 0.        , 0.57735027, 0.        ],
       [0.61366674, 0.        , 0.        , 0.61366674, 0.49681612]])

In [34]:
print(tf.idf_)

[1.51082562 1.51082562 1.51082562 1.51082562 1.22314355]
